### ISSUE TITLE
Cloudflare denies some users

### ISSUE THREAD

**Issue by breerly** [uber/go.uber.org#28]
Originally reported at: https://github.com/uber-go/zap/issues/451

From a discussion with @billf -

> ... might have something to do with cloudlfare thinking the person is coming from a bad IP and throwing up some sort of roadblock. cloud providers with known spammers...

**Comment by billf** [comment]
i've disabled [Browser Integrity Check](https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-) on the domain. since we haven't come up with a reproduce case, i can't verify but it should help.

**Comment by breerly** [comment]
I'm satisfied with that for now.

If the issue persists, we can reopen the issue.

**Comment by piotrkowalczuk** [comment]
@breerly it happened to me juz recently
