### ISSUE TITLE
go.uber.org is down?

### ISSUE THREAD

**Issue by scottjbarr** [uber/go.uber.org#32]
It looks like go.uber.org is down.

https://downforeveryoneorjustme.com/go.uber.org

**Comment by scottjbarr** [comment]
And it's up again :)

**Comment by hnakamur** [comment]
https://downforeveryoneorjustme.com/go.uber.org
still prints "It's not just you!".

I tweeted https://twitter.com/hnakamur2/status/970895456325677056 at UberEng on twitter.

**Comment by take-cheeze** [comment]
Seems like DNS is wrong?
```
$ dig @8.8.8.8 go.uber.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @8.8.8.8 go.uber.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64143
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;go.uber.org.                   IN      A

;; ANSWER SECTION:
go.uber.org.            299     IN      A       104.28.1.50
go.uber.org.            299     IN      A       104.28.0.50

;; Query time: 50 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Mar 06 14:43:51 DST 2018
;; MSG SIZE  rcvd: 72

$ dig go.uber.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> go.uber.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 62948
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;go.uber.org.                   IN      A

;; Query time: 0 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Tue Mar 06 14:43:56 DST 2018
;; MSG SIZE  rcvd: 29

```

**Comment by hnakamur** [comment]
My trial results:

```
$ dig go.uber.org ns
                                          
; <<>> DiG 9.10.3-P4-Ubuntu <<>> go.uber.org ns
;; global options: +cmd
;; Got answer:                                                                                                        
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 4067
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
                                      
;; OPT PSEUDOSECTION:                
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;go.uber.org.                   IN      NS

;; AUTHORITY SECTION:                       
uber.org.               1371    IN      SOA     pdns80.ultradns.com. bigo.uber.com. 2014031649 86400 86400 86400 86400
              
;; Query time: 10 msec                                   
;; SERVER: 10.155.92.1#53(10.155.92.1)                              
;; WHEN: Tue Mar 06 15:03:25 JST 2018
;; MSG SIZE  rcvd: 105
```

```
$ dig uber.org ns
                                          
; <<>> DiG 9.10.3-P4-Ubuntu <<>> uber.org ns
;; global options: +cmd
;; Got answer:                                                      
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12620           
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
                                                                    
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:                  
;uber.org.                      IN      NS
                      
;; ANSWER SECTION:
uber.org.               84170   IN      NS      pdns80.ultradns.net.
uber.org.               84170   IN      NS      pdns80.ultradns.com.
uber.org.               84170   IN      NS      pdns80.ultradns.org.
uber.org.               84170   IN      NS      pdns80.ultradns.biz.
                       
;; Query time: 9 msec
;; SERVER: 10.155.92.1#53(10.155.92.1)                    
;; WHEN: Tue Mar 06 15:03:30 JST 2018                               
;; MSG SIZE  rcvd: 166
```

```
$ dig @pdns80.ultradns.net go.uber.org
                                      
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @pdns80.ultradns.net go.uber.org
; (2 servers found)                      
;; global options: +cmd
;; Got answer:       
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 48656                                                            
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available
                                                
;; OPT PSEUDOSECTION:                
; EDNS: version: 0, flags:; udp: 65235
;; QUESTION SECTION:
;go.uber.org.                   IN      A

;; AUTHORITY SECTION:
uber.org.               86400   IN      SOA     pdns80.ultradns.com. bigo.uber.com. 2014031649 86400 86400 86400 86400

;; Query time: 21 msec
;; SERVER: 2610:a1:1014::74#53(2610:a1:1014::74)
;; WHEN: Tue Mar 06 15:03:44 JST 2018
;; MSG SIZE  rcvd: 105
```

**Comment by breerly** [comment]
Getting ahold of @billf to triage.

**Comment by scottjbarr** [comment]
Looks like I closed this one too early.

**Comment by tsuna** [comment]
Please stand by while Uber is left-padding the Go community :trollface:

**Comment by breerly** [comment]
Registrar issue, please stand by.

**Comment by AleksandrGreen** [comment]
Not working too.
Please make possible to installation Zap with Github via dep:
dep ensure -add github.com/uber/go.uber.org

**Comment by breerly** [comment]
The issue is now resolved - please allow some time for DNS cache to propagate.

Sorry to all our Gopher friends out there.

https://downforeveryoneorjustme.com/go.uber.org

![screen shot 2018-03-05 at 11 40 56 pm](https://user-images.githubusercontent.com/263587/37019887-d0287b62-20ce-11e8-85d5-55f000bd017b.png)

**Comment by gwake1** [comment]
experiencing this issue as well

**Comment by gwake1** [comment]
dig go.uber.org ns

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.5 <<>> go.uber.org ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47568
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;go.uber.org.                   IN      NS

;; AUTHORITY SECTION:
uber.org.               900     IN      SOA     gwen.ns.cloudflare.com. dns.cloudflare.com. 2026846050 10000 2400 604800 3600

;; Query time: 37 msec
;; SERVER: 10.26.60.151#53(10.26.60.151)
;; WHEN: Mon Apr 16 13:02:27 2018
;; MSG SIZE  rcvd: 91

**Comment by billf** [comment]
@gwake1 `go.uber.org` does not have NS records as we do not delegate control away from the standard `uber.org` nameservers for `go.uber.org`. `dig uber.org ns` and `dig go.uber.org a` will show the expected behavior. if you're having an issue with `go.uber.org`, please open a new issue.

in general, use `dig +trace` when reporting DNS issues. `+trace` will show the results step by step from the root delegation. the behavior of the recursive resolver your host is pointed at may have localized configurations, avoid showing the results of querying a DNS server that is inaccessible from the public.

`dig +trace -t a go.uber.org` provides all the information required to show that `go.uber.org` resolution is working as expected.

**Comment by breerly** [comment]
Circling back to let everyone know that we've added global ping-based alerts to this domain - if it goes down again in the future, we'll be the first to know ⚡️ 

That being said, this is more of a fail-safe - we've don't foresee another issue like this in the future.
